# Generated by Django 6.0.3 on 2026-03-26 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_security_seed_roles_and_encrypt_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='alert_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['crop'], name='alert_crop_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['tag'], name='alert_tag_idx'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['category'], name='guide_category_idx'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['badge'], name='guide_badge_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['owner', 'sender'], name='sm_owner_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['sender'], name='sm_sender_idx'),
        ),
    ]
