# Generated by Django 6.0.3 on 2026-04-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cropoption_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
